repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.60.1
    hooks:
      - id: golangci-lint-full
        name: Lint golang files
        args: ["--fix"]

  - repo: local
    hooks:
      - id: gotest
        name: Run tests
        alias: gotest
        entry: make test
        language: system
        always_run: true
        stages: [commit, push]
