CREATE TABLE apikeys (
  id SERIAL PRIMARY KEY,
  public_id VARCHAR(15) NOT NULL UNIQUE,
  name VARCHAR(64) NOT NULL,
  key VARCHAR(128) NOT NULL,
  revoked BOOLEAN NOT NULL DEFAULT FALSE,
  revoked_at TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
