// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: chikitos.sql

package postgres

import (
	"context"
)

const createChikito = `-- name: CreateChikito :one
INSERT INTO chikitos (public_id, url, description) VALUES ($1, $2, $3) RETURNING id, public_id, url, description, created_at, updated_at
`

type CreateChikitoParams struct {
	PublicID    string
	Url         string
	Description string
}

func (q *Queries) CreateChikito(ctx context.Context, arg CreateChikitoParams) (Chikito, error) {
	row := q.db.QueryRow(ctx, createChikito, arg.PublicID, arg.Url, arg.Description)
	var i Chikito
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Url,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChikito = `-- name: GetChikito :one
SELECT id, public_id, url, description, created_at, updated_at FROM chikitos WHERE public_id = $1
`

func (q *Queries) GetChikito(ctx context.Context, publicID string) (Chikito, error) {
	row := q.db.QueryRow(ctx, getChikito, publicID)
	var i Chikito
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Url,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
