name: Test GoYurback

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - internal/**
  pull_request:
    branches-ignore:
      - production
    paths:
      - internal/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go 1.22.x
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Install modules
        run: go mod download
      - name: Run tests
        run: |
          go test -race -covermode=atomic -coverprofile=coverage.out ./...
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
